stages:
  build_docker:
    cmd: docker build -t moe-rl-app .
    deps:
      - src/
      - Dockerfile
      - requirements.txt

  prepare_data:
    cmd: ./run_in_docker.sh prepare_data
    deps:
      - src/pipeline.py
      - src/models/data_preparer.py
      - run_in_docker.sh
    outs:
      - data/raw/gsm8k

  run_pipeline:
    cmd: ./run_in_docker.sh full_pipeline
    deps:
      - src/
      - data/raw/gsm8k
      - run_in_docker.sh
